// =============================================================================
// Bindery — view code generator. Pure generation (ViewModel in → C# string out):
//   • <Name>View.g.cs — `public partial class FooView : Bindery.BinderyView` with a
//     [SerializeField] reference + a typed accessor per bindable child, and a nested
//     scope class per container (view.Footer.OkButton).
//   • <Name>View.cs   — a one-time, editable behaviour stub (write-if-absent) in the
//     SAME assembly so OnBind() + your code compile against the generated partial.
//   • Bindery.Generated.asmdef — isolates generated code, referenceable from your own
//     assembly definitions.
//
// References are wired on the live object by BinderyWire after compile; the
// generated accessors are therefore plain field reads — no registry, no Find.
// =============================================================================

using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace Bindery
{
    internal static class BinderyCodeGen
    {
        // Default generated namespace / base class. The configured values ride on the ViewModel
        // (BinderySettings.GeneratedNamespace / .BaseClass); these consts are the fallbacks used when
        // a model leaves them unset and the canonical default the asmdef ships with.
        public const string GeneratedNamespace = "Bindery.Generated";
        public const string DefaultBaseClass = "Bindery.BinderyView";

        // The configured namespace / base class for a view, defaulting when the model didn't set them.
        static string NamespaceOf(ViewModel v) => string.IsNullOrEmpty(v.namespaceName) ? GeneratedNamespace : v.namespaceName;
        static string BaseClassOf(ViewModel v) => string.IsNullOrEmpty(v.baseClass) ? DefaultBaseClass : v.baseClass;

        // ---- <Name>View.g.cs ----------------------------------------------------------
        public static string EmitViewClass(ViewModel v)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Bindery accessor view — regenerated on demand. Do not edit.");
            sb.AppendLine("// Add behaviour in the editable " + v.className + ".cs (in the Views folder, NOT regenerated):");
            sb.AppendLine("//   public partial class " + v.className + " { protected override void OnBind() { } }");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace " + NamespaceOf(v));
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + v.className + " : " + BaseClassOf(v));
            sb.AppendLine("    {");

            // Backing fields (flat on the view; nested scopes index back into these). Collected
            // members keep their own [SerializeField] (still wired one-by-one); the lead of each
            // group also gets a cached IReadOnlyList<T> field the collection accessor lazy-fills.
            foreach (var m in v.members)
            {
                sb.AppendLine("        [SerializeField] " + m.csharpType + " " + m.FieldName + ";");
                if (m.isScope)
                    sb.AppendLine("        " + m.scopeTypeName + " " + m.FieldName + "Scope;");
                if (m.collectionLead)
                    sb.AppendLine("        " + ReadOnlyListType(m.csharpType) + " " + CollectionField(m) + ";");
            }
            if (v.members.Count > 0) sb.AppendLine();

            // Accessors exposed directly on the view (top-level children). A collected member's
            // individual accessor is suppressed in favour of the group's collection accessor, which
            // the lead element emits in element-index order.
            foreach (var m in v.members)
            {
                if (!m.exposeOnRoot) continue;
                if (m.IsCollected)
                {
                    if (m.collectionLead)
                        sb.AppendLine(EmitCollectionAccessor(v, m, "        ", ""));
                    continue;
                }
                if (m.isScope)
                    sb.AppendLine("        public " + m.scopeTypeName + " " + m.identifier
                                + " => " + m.FieldName + "Scope ??= new " + m.scopeTypeName + "(this);");
                else
                    sb.AppendLine("        public " + m.csharpType + " " + m.identifier + " => " + m.FieldName + ";");
            }

            // One nested class per container scope, exposing its direct children.
            foreach (var s in v.members)
            {
                if (!s.isScope) continue;
                sb.AppendLine();
                sb.AppendLine("        public sealed class " + s.scopeTypeName);
                sb.AppendLine("        {");
                sb.AppendLine("            readonly " + v.className + " _view;");
                sb.AppendLine("            internal " + s.scopeTypeName + "(" + v.className + " view) { _view = view; }");
                sb.AppendLine("            public RectTransform RectTransform => _view." + s.FieldName + ";");
                sb.AppendLine("            public GameObject GameObject => _view." + s.FieldName + " != null ? _view." + s.FieldName + ".gameObject : null;");
                foreach (var c in v.members)
                {
                    if (c.parent != s.node) continue;
                    if (c.IsCollected)
                    {
                        // Collection backing field lives flat on the view; the accessor surfaces here.
                        if (c.collectionLead)
                            sb.AppendLine(EmitCollectionAccessor(v, c, "            ", "_view."));
                        continue;
                    }
                    if (c.isScope)
                        sb.AppendLine("            public " + c.scopeTypeName + " " + c.identifier
                                    + " => _view." + c.FieldName + "Scope ??= new " + c.scopeTypeName + "(_view);");
                    else
                        sb.AppendLine("            public " + c.csharpType + " " + c.identifier + " => _view." + c.FieldName + ";");
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---- collection emit helpers --------------------------------------------------
        // A collected group surfaces as one cached, read-only, ordered accessor:
        //   public IReadOnlyList<Button> Slots => _Slots ??= new Button[] { _Slot0, _Slot1, _Slot2 };
        // Elements are gathered from the group's members (lead + the rest) in parsed-index order.
        // <paramref name="indent"/> sets the surrounding indent; <paramref name="fieldPrefix"/> is
        // "" on the view body or "_view." inside a scope class (the fields are flat on the view).
        static string EmitCollectionAccessor(ViewModel v, ViewMember lead, string indent, string fieldPrefix)
        {
            var group = new List<ViewMember>();
            foreach (var m in v.members)
                if (m.collectionName == lead.collectionName && m.parent == lead.parent && m.csharpType == lead.csharpType)
                    group.Add(m);
            group.Sort((a, b) => a.collectionIndex.CompareTo(b.collectionIndex));

            var elems = new StringBuilder();
            for (int i = 0; i < group.Count; i++)
            {
                if (i > 0) elems.Append(", ");
                elems.Append(fieldPrefix).Append(group[i].FieldName);
            }

            string listType = ReadOnlyListType(lead.csharpType);
            return indent + "public " + listType + " " + lead.collectionName
                 + " => " + fieldPrefix + CollectionField(lead)
                 + " ??= new " + lead.csharpType + "[] { " + elems + " };";
        }

        // The cached array field name for a group, e.g. "_Slots" (flat on the view, like backing fields).
        static string CollectionField(ViewMember lead) => "_" + lead.collectionName;

        static string ReadOnlyListType(string elementType)
            => "System.Collections.Generic.IReadOnlyList<" + elementType + ">";

        // ---- <Name>View.cs (editable stub, written only if missing) -------------------
        // Optionally pre-wires each control's basic event to a named handler method (with its own
        // body) so the developer has somewhere to put behaviour. Written once, never regenerated.
        public static string EmitBehaviourStub(ViewModel v, bool scaffoldButtons, bool scaffoldControls)
        {
            // scope node → its member, so we can build access paths like "Footer.OkButton".
            var scopeByNode = new Dictionary<Transform, ViewMember>();
            foreach (var m in v.members) if (m.isScope && m.node != null) scopeByNode[m.node] = m;

            var handlers = new List<Handler>();
            foreach (var m in v.members)
            {
                if (m.isScope) continue;
                if (m.IsCollected && !m.collectionLead) continue;          // a collection is scaffolded once, on its lead
                var ev = ControlEvent(m.csharpType);
                if (ev == null) continue;                                  // graphics / sub-views: no event
                bool isButton = m.csharpType == "UnityEngine.UI.Button";
                if (isButton ? !scaffoldButtons : !scaffoldControls) continue;
                bool hasValue = !string.IsNullOrEmpty(ev.ParamDecl);
                if (m.IsCollected)
                    // a collection: wire every element in a loop to one indexed handler
                    handlers.Add(new Handler
                    {
                        isCollection = true,
                        hasValue = hasValue,
                        access = CollectionAccessPath(m, scopeByNode),
                        evt = ev.EventName,
                        name = "On" + m.collectionName + ev.Suffix,
                        param = hasValue ? "int index, " + ev.ParamDecl : "int index",
                        todo = "handle " + m.collectionName + "[index] " + ev.Action,
                    });
                else
                    handlers.Add(new Handler
                    {
                        access = AccessPath(m, scopeByNode),
                        evt = ev.EventName,
                        name = "On" + m.Key + ev.Suffix,
                        param = ev.ParamDecl,
                        todo = "handle " + m.Key + " " + ev.Action,
                    });
            }

            var sb = new StringBuilder();
            sb.AppendLine("// Your code for " + v.className + ". This file is NOT regenerated — safe to edit.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace " + NamespaceOf(v));
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + v.className);
            sb.AppendLine("    {");
            sb.AppendLine("        // Runs once before Awake completes, after references are wired.");
            sb.AppendLine("        protected override void OnBind()");
            sb.AppendLine("        {");
            if (handlers.Count == 0)
                sb.AppendLine("            // TODO: bind events here, e.g. someButton.onClick.AddListener(() => { });");
            else
                foreach (var h in handlers)
                {
                    if (h.isCollection)
                    {
                        string lambda = h.hasValue ? "value => " + h.name + "(index, value)" : "() => " + h.name + "(index)";
                        sb.AppendLine("            for (int i = 0; i < " + h.access + ".Count; i++)");
                        sb.AppendLine("            {");
                        sb.AppendLine("                int index = i;");
                        sb.AppendLine("                " + h.access + "[i]." + h.evt + ".AddListener(" + lambda + ");");
                        sb.AppendLine("            }");
                    }
                    else
                        sb.AppendLine("            " + h.access + "." + h.evt + ".AddListener(" + h.name + ");");
                }
            sb.AppendLine("        }");

            foreach (var h in handlers)
            {
                sb.AppendLine();
                sb.AppendLine("        void " + h.name + "(" + h.param + ")");
                sb.AppendLine("        {");
                sb.AppendLine("            // TODO: " + h.todo);
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        sealed class Handler { public string access, evt, name, param, todo; public bool isCollection, hasValue; }
        sealed class ControlEvt { public string EventName, ParamDecl, Suffix, Action; }

        // The basic event Bindery scaffolds per control type — null for graphics / scopes / sub-views.
        static ControlEvt ControlEvent(string csharpType)
        {
            switch (csharpType)
            {
                case "UnityEngine.UI.Button":     return new ControlEvt { EventName = "onClick", ParamDecl = "", Suffix = "Clicked", Action = "click" };
                case "UnityEngine.UI.Toggle":     return Changed("bool");
                case "UnityEngine.UI.Slider":     return Changed("float");
                case "UnityEngine.UI.Scrollbar":  return Changed("float");
                case "UnityEngine.UI.Dropdown":   return Changed("int");
                case "TMPro.TMP_Dropdown":        return Changed("int");
                case "UnityEngine.UI.InputField": return Changed("string");
                case "TMPro.TMP_InputField":      return Changed("string");
                case "UnityEngine.UI.ScrollRect": return Changed("Vector2");
                default:                          return null;
            }
        }

        static ControlEvt Changed(string paramType) =>
            new ControlEvt { EventName = "onValueChanged", ParamDecl = paramType + " value", Suffix = "Changed", Action = "value change" };

        // "Footer.OkButton" etc. — the chain of scope accessors from the root down to the control.
        static string AccessPath(ViewMember m, Dictionary<Transform, ViewMember> scopeByNode)
        {
            if (m.exposeOnRoot) return m.identifier;
            if (m.parent != null && scopeByNode.TryGetValue(m.parent, out var scope))
                return AccessPath(scope, scopeByNode) + "." + m.identifier;
            return m.identifier; // defensive: every non-root member should resolve to a scope
        }

        // Like AccessPath, but to a collection accessor (e.g. "Slots" / "Footer.Slots") — the group
        // surfaces under its lead's effective parent named after the collection, not the element.
        static string CollectionAccessPath(ViewMember lead, Dictionary<Transform, ViewMember> scopeByNode)
        {
            if (lead.exposeOnRoot) return lead.collectionName;
            if (lead.parent != null && scopeByNode.TryGetValue(lead.parent, out var scope))
                return AccessPath(scope, scopeByNode) + "." + lead.collectionName;
            return lead.collectionName;
        }

        // ---- Bindery.Generated.asmdef -------------------------------------------------
        // The built-in references every generated view needs. Custom-component views ([BinderyBind])
        // add the assembly that defines the component on top — passed in via extraAssemblyRefs.
        static readonly string[] BaseAsmdefRefs = { "Bindery.Runtime", "UnityEngine.UI", "Unity.TextMeshPro" };

        /// <summary>Emit the Bindery.Generated asmdef JSON. The assembly NAME stays "Bindery.Generated"
        /// (its identity — referenced by user asmdefs and the wiring); <paramref name="rootNamespace"/>
        /// tracks the configured generated namespace. <paramref name="extraAssemblyRefs"/> are the
        /// assemblies that define any [BinderyBind] custom components surfaced by the generated views;
        /// they're merged after the built-ins and de-duped so a custom-component view actually compiles.
        /// CAVEAT: an extra assembly must NOT reference Bindery.Generated back, or Unity rejects the
        /// cyclic asmdef — keep [BinderyBind] components in their own leaf assembly (v1 limitation).</summary>
        public static string EmitAsmdef(IEnumerable<string> extraAssemblyRefs = null, string rootNamespace = GeneratedNamespace)
        {
            // Built-ins first, then extras in first-seen order, skipping blanks/dupes.
            var refs = new List<string>(BaseAsmdefRefs);
            var seen = new HashSet<string>(refs);
            if (extraAssemblyRefs != null)
                foreach (var r in extraAssemblyRefs)
                    if (!string.IsNullOrEmpty(r) && seen.Add(r)) refs.Add(r);

            var sb = new StringBuilder();
            sb.Append("{\n");
            sb.Append("  \"name\": \"Bindery.Generated\",\n");
            sb.Append("  \"rootNamespace\": \"").Append(string.IsNullOrEmpty(rootNamespace) ? GeneratedNamespace : rootNamespace).Append("\",\n");
            sb.Append("  \"references\": [\n");
            for (int i = 0; i < refs.Count; i++)
                sb.Append("    \"").Append(refs[i]).Append(i < refs.Count - 1 ? "\",\n" : "\"\n");
            sb.Append("  ],\n");
            sb.Append("  \"autoReferenced\": true\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
