// =============================================================================
// Bindery — view code generator. Pure generation (ViewModel in → C# string out):
//   • <Name>View.g.cs — `public partial class FooView : Bindery.BinderyView` with a
//     [SerializeField] reference + a typed accessor per bindable child, and a nested
//     scope class per container (view.Footer.OkButton).
//   • <Name>View.cs   — a one-time, editable behaviour stub (write-if-absent) in the
//     SAME assembly so OnBind() + your code compile against the generated partial.
//   • Bindery.Generated.asmdef — isolates generated code, referenceable from your own
//     assembly definitions.
//
// References are wired on the live object by BinderyWire after compile; the
// generated accessors are therefore plain field reads — no registry, no Find.
// =============================================================================

using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace Bindery
{
    internal static class BinderyCodeGen
    {
        public const string GeneratedNamespace = "Bindery.Generated";

        // ---- <Name>View.g.cs ----------------------------------------------------------
        public static string EmitViewClass(ViewModel v)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Bindery accessor view — regenerated on demand. Do not edit.");
            sb.AppendLine("// Add behaviour in the editable " + v.className + ".cs (in the Views folder, NOT regenerated):");
            sb.AppendLine("//   public partial class " + v.className + " { protected override void OnBind() { } }");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + v.className + " : Bindery.BinderyView");
            sb.AppendLine("    {");

            // Backing fields (flat on the view; nested scopes index back into these).
            foreach (var m in v.members)
            {
                sb.AppendLine("        [SerializeField] " + m.csharpType + " " + m.FieldName + ";");
                if (m.isScope)
                    sb.AppendLine("        " + m.scopeTypeName + " " + m.FieldName + "Scope;");
            }
            if (v.members.Count > 0) sb.AppendLine();

            // Accessors exposed directly on the view (top-level children).
            foreach (var m in v.members)
            {
                if (!m.exposeOnRoot) continue;
                if (m.isScope)
                    sb.AppendLine("        public " + m.scopeTypeName + " " + m.identifier
                                + " => " + m.FieldName + "Scope ??= new " + m.scopeTypeName + "(this);");
                else
                    sb.AppendLine("        public " + m.csharpType + " " + m.identifier + " => " + m.FieldName + ";");
            }

            // One nested class per container scope, exposing its direct children.
            foreach (var s in v.members)
            {
                if (!s.isScope) continue;
                sb.AppendLine();
                sb.AppendLine("        public sealed class " + s.scopeTypeName);
                sb.AppendLine("        {");
                sb.AppendLine("            readonly " + v.className + " _view;");
                sb.AppendLine("            internal " + s.scopeTypeName + "(" + v.className + " view) { _view = view; }");
                sb.AppendLine("            public RectTransform RectTransform => _view." + s.FieldName + ";");
                sb.AppendLine("            public GameObject GameObject => _view." + s.FieldName + " != null ? _view." + s.FieldName + ".gameObject : null;");
                foreach (var c in v.members)
                {
                    if (c.parent != s.node) continue;
                    if (c.isScope)
                        sb.AppendLine("            public " + c.scopeTypeName + " " + c.identifier
                                    + " => _view." + c.FieldName + "Scope ??= new " + c.scopeTypeName + "(_view);");
                    else
                        sb.AppendLine("            public " + c.csharpType + " " + c.identifier + " => _view." + c.FieldName + ";");
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---- <Name>View.cs (editable stub, written only if missing) -------------------
        // Optionally pre-wires each control's basic event to a named handler method (with its own
        // body) so the developer has somewhere to put behaviour. Written once, never regenerated.
        public static string EmitBehaviourStub(ViewModel v, bool scaffoldButtons, bool scaffoldControls)
        {
            // scope node → its member, so we can build access paths like "Footer.OkButton".
            var scopeByNode = new Dictionary<Transform, ViewMember>();
            foreach (var m in v.members) if (m.isScope && m.node != null) scopeByNode[m.node] = m;

            var handlers = new List<Handler>();
            foreach (var m in v.members)
            {
                if (m.isScope) continue;
                var ev = ControlEvent(m.csharpType);
                if (ev == null) continue;                                  // graphics / sub-views: no event
                bool isButton = m.csharpType == "UnityEngine.UI.Button";
                if (isButton ? !scaffoldButtons : !scaffoldControls) continue;
                handlers.Add(new Handler
                {
                    access = AccessPath(m, scopeByNode),
                    evt = ev.EventName,
                    name = "On" + m.Key + ev.Suffix,
                    param = ev.ParamDecl,
                    todo = "handle " + m.Key + " " + ev.Action,
                });
            }

            var sb = new StringBuilder();
            sb.AppendLine("// Your code for " + v.className + ". This file is NOT regenerated — safe to edit.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + v.className);
            sb.AppendLine("    {");
            sb.AppendLine("        // Runs once before Awake completes, after references are wired.");
            sb.AppendLine("        protected override void OnBind()");
            sb.AppendLine("        {");
            if (handlers.Count == 0)
                sb.AppendLine("            // TODO: bind events here, e.g. someButton.onClick.AddListener(() => { });");
            else
                foreach (var h in handlers)
                    sb.AppendLine("            " + h.access + "." + h.evt + ".AddListener(" + h.name + ");");
            sb.AppendLine("        }");

            foreach (var h in handlers)
            {
                sb.AppendLine();
                sb.AppendLine("        void " + h.name + "(" + h.param + ")");
                sb.AppendLine("        {");
                sb.AppendLine("            // TODO: " + h.todo);
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        sealed class Handler { public string access, evt, name, param, todo; }
        sealed class ControlEvt { public string EventName, ParamDecl, Suffix, Action; }

        // The basic event Bindery scaffolds per control type — null for graphics / scopes / sub-views.
        static ControlEvt ControlEvent(string csharpType)
        {
            switch (csharpType)
            {
                case "UnityEngine.UI.Button":     return new ControlEvt { EventName = "onClick", ParamDecl = "", Suffix = "Clicked", Action = "click" };
                case "UnityEngine.UI.Toggle":     return Changed("bool");
                case "UnityEngine.UI.Slider":     return Changed("float");
                case "UnityEngine.UI.Scrollbar":  return Changed("float");
                case "UnityEngine.UI.Dropdown":   return Changed("int");
                case "TMPro.TMP_Dropdown":        return Changed("int");
                case "UnityEngine.UI.InputField": return Changed("string");
                case "TMPro.TMP_InputField":      return Changed("string");
                case "UnityEngine.UI.ScrollRect": return Changed("Vector2");
                default:                          return null;
            }
        }

        static ControlEvt Changed(string paramType) =>
            new ControlEvt { EventName = "onValueChanged", ParamDecl = paramType + " value", Suffix = "Changed", Action = "value change" };

        // "Footer.OkButton" etc. — the chain of scope accessors from the root down to the control.
        static string AccessPath(ViewMember m, Dictionary<Transform, ViewMember> scopeByNode)
        {
            if (m.exposeOnRoot) return m.identifier;
            if (m.parent != null && scopeByNode.TryGetValue(m.parent, out var scope))
                return AccessPath(scope, scopeByNode) + "." + m.identifier;
            return m.identifier; // defensive: every non-root member should resolve to a scope
        }

        // ---- Bindery.Generated.asmdef -------------------------------------------------
        public static string EmitAsmdef()
        {
            return "{\n"
                 + "  \"name\": \"Bindery.Generated\",\n"
                 + "  \"rootNamespace\": \"Bindery.Generated\",\n"
                 + "  \"references\": [\n"
                 + "    \"Bindery.Runtime\",\n"
                 + "    \"UnityEngine.UI\",\n"
                 + "    \"Unity.TextMeshPro\"\n"
                 + "  ],\n"
                 + "  \"autoReferenced\": true\n"
                 + "}\n";
        }
    }
}
