// =============================================================================
// Bindery — view code generator. Pure generation (ViewModel in → C# string out):
//   • <Name>View.g.cs — `public partial class FooView : Bindery.BinderyView` with a
//     [SerializeField] reference + a typed accessor per bindable child, and a nested
//     scope class per container (view.Footer.OkButton).
//   • <Name>View.cs   — a one-time, editable behaviour stub (write-if-absent) in the
//     SAME assembly so OnBind() + your code compile against the generated partial.
//   • Bindery.Generated.asmdef — isolates generated code, referenceable from your own
//     assembly definitions.
//
// References are wired on the live object by BinderyWire after compile; the
// generated accessors are therefore plain field reads — no registry, no Find.
// =============================================================================

using System.Text;

namespace Bindery
{
    internal static class BinderyCodeGen
    {
        public const string GeneratedNamespace = "Bindery.Generated";

        // ---- <Name>View.g.cs ----------------------------------------------------------
        public static string EmitViewClass(ViewModel v)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Bindery accessor view — regenerated on demand. Do not edit.");
            sb.AppendLine("// Add behaviour in the sibling " + v.className + ".cs (NOT regenerated):");
            sb.AppendLine("//   public partial class " + v.className + " { protected override void OnBind() { } }");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + v.className + " : Bindery.BinderyView");
            sb.AppendLine("    {");

            // Backing fields (flat on the view; nested scopes index back into these).
            foreach (var m in v.members)
            {
                sb.AppendLine("        [SerializeField] " + m.csharpType + " " + m.FieldName + ";");
                if (m.isScope)
                    sb.AppendLine("        " + m.scopeTypeName + " " + m.FieldName + "Scope;");
            }
            if (v.members.Count > 0) sb.AppendLine();

            // Accessors exposed directly on the view (top-level children).
            foreach (var m in v.members)
            {
                if (!m.exposeOnRoot) continue;
                if (m.isScope)
                    sb.AppendLine("        public " + m.scopeTypeName + " " + m.identifier
                                + " => " + m.FieldName + "Scope ??= new " + m.scopeTypeName + "(this);");
                else
                    sb.AppendLine("        public " + m.csharpType + " " + m.identifier + " => " + m.FieldName + ";");
            }

            // One nested class per container scope, exposing its direct children.
            foreach (var s in v.members)
            {
                if (!s.isScope) continue;
                sb.AppendLine();
                sb.AppendLine("        public sealed class " + s.scopeTypeName);
                sb.AppendLine("        {");
                sb.AppendLine("            readonly " + v.className + " _view;");
                sb.AppendLine("            internal " + s.scopeTypeName + "(" + v.className + " view) { _view = view; }");
                sb.AppendLine("            public RectTransform RectTransform => _view." + s.FieldName + ";");
                sb.AppendLine("            public GameObject GameObject => _view." + s.FieldName + " != null ? _view." + s.FieldName + ".gameObject : null;");
                foreach (var c in v.members)
                {
                    if (c.parent != s.node) continue;
                    if (c.isScope)
                        sb.AppendLine("            public " + c.scopeTypeName + " " + c.identifier
                                    + " => _view." + c.FieldName + "Scope ??= new " + c.scopeTypeName + "(_view);");
                    else
                        sb.AppendLine("            public " + c.csharpType + " " + c.identifier + " => _view." + c.FieldName + ";");
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---- <Name>View.cs (editable stub, written only if missing) -------------------
        public static string EmitBehaviourStub(ViewModel v)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Your code for " + v.className + ". This file is NOT regenerated — safe to edit.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + v.className);
            sb.AppendLine("    {");
            sb.AppendLine("        // Runs once before Awake completes, after references are wired.");
            sb.AppendLine("        protected override void OnBind()");
            sb.AppendLine("        {");
            sb.AppendLine("            // e.g. someButton.onClick.AddListener(() => Debug.Log(\"clicked\"));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---- Bindery.Generated.asmdef -------------------------------------------------
        public static string EmitAsmdef()
        {
            return "{\n"
                 + "  \"name\": \"Bindery.Generated\",\n"
                 + "  \"rootNamespace\": \"Bindery.Generated\",\n"
                 + "  \"references\": [\n"
                 + "    \"Bindery.Runtime\",\n"
                 + "    \"UnityEngine.UI\",\n"
                 + "    \"Unity.TextMeshPro\"\n"
                 + "  ],\n"
                 + "  \"autoReferenced\": true\n"
                 + "}\n";
        }
    }
}
